// native-slicer.test.js — Verify the pure-JS slicer pipeline produces
// valid layer polygons + reasonable G-code for simple shapes.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import {
  sliceLayer, offsetPolygon, lineInfill, layersToGcode, sliceMeshToGcode, seamStart, _internals,
} from '../../server/native-slicer.js';
import { patternInfill } from '../../server/native-slicer-geo.js';
import { box, cylinder } from '../../server/mesh-primitives.js';

describe('native-slicer: sliceLayer', () => {
  it('a 10mm cube cut at z=5 yields one square polygon', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, 5);
    assert.ok(polys.length >= 1, 'at least one polygon');
    // Square outline — 4 corners + up to 4 midpoint vertices from
    // diagonal edges of split-quad faces (8 total). Still a square.
    const total = polys[0].length;
    assert.ok(total >= 4 && total <= 12, `expected 4-12 vertices, got ${total}`);
    // Verify it spans the full 10×10 outline.
    const xs = polys[0].map(p => p[0]);
    const ys = polys[0].map(p => p[1]);
    assert.equal(Math.min(...xs), 0);
    assert.equal(Math.max(...xs), 10);
    assert.equal(Math.min(...ys), 0);
    assert.equal(Math.max(...ys), 10);
  });

  it('cube cut above its top z returns empty', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, 12);
    assert.equal(polys.length, 0);
  });

  it('cube cut below its bottom z returns empty', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, -1);
    assert.equal(polys.length, 0);
  });

  it('cylinder cut at mid-height yields a many-vertex polygon', () => {
    const cyl = cylinder(10, 20, 32);
    const polys = sliceLayer(cyl, 10);
    assert.ok(polys.length >= 1);
    assert.ok(polys[0].length > 16, `cylinder polygon should have many vertices, got ${polys[0].length}`);
  });
});

describe('native-slicer: offsetPolygon', () => {
  it('shrinking a square by 1 produces a smaller square', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const inner = offsetPolygon(square, -1);
    assert.equal(inner.length, 4);
    // Each corner moves inward by ~1 unit along the bisector.
    const minX = Math.min(...inner.map(p => p[0]));
    const maxX = Math.max(...inner.map(p => p[0]));
    assert.ok(Math.abs(minX - 1) < 0.1, `inner left should be ~1, got ${minX}`);
    assert.ok(Math.abs(maxX - 9) < 0.1, `inner right should be ~9, got ${maxX}`);
  });

  it('growing a square by 1 produces a larger square', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const outer = offsetPolygon(square, 1);
    assert.equal(outer.length, 4);
    const minX = Math.min(...outer.map(p => p[0]));
    const maxX = Math.max(...outer.map(p => p[0]));
    assert.ok(minX < -0.5 && maxX > 10.5);
  });

  it('returns empty for degenerate (over-shrunk) polygon', () => {
    const tinySquare = [[0, 0], [2, 0], [2, 2], [0, 2]];
    const inner = offsetPolygon(tinySquare, -10);
    assert.deepEqual(inner, []);
  });
});

describe('native-slicer: lineInfill', () => {
  it('generates parallel hatching segments inside a square', () => {
    const square = [[0, 0], [20, 0], [20, 20], [0, 20]];
    const segs = lineInfill(square, 0.3, 45, 0.4);
    assert.ok(segs.length > 0);
    // Each segment is two points.
    for (const s of segs) {
      assert.equal(s.length, 2);
      assert.equal(s[0].length, 2);
    }
  });

  it('zero density returns empty', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const segs = lineInfill(square, 0, 0, 0.4);
    assert.deepEqual(segs, []);
  });
});

describe('native-slicer: layersToGcode', () => {
  it('emits valid G-code skeleton with header + finisher', () => {
    const layers = [
      { perimeters: [[[0, 0], [10, 0], [10, 10], [0, 10]]], infill: [] },
    ];
    const gcode = layersToGcode(layers, { layerHeight: 0.2, nozzleTemp: 210, bedTemp: 60 });
    assert.match(gcode, /M104 S210/);
    assert.match(gcode, /M140 S60/);
    assert.match(gcode, /G28/);
    assert.match(gcode, /G1 X10\.000 Y0\.000/);   // perimeter move
    assert.match(gcode, /M104 S0/);               // cooldown
    assert.match(gcode, /M84/);                   // motors off
  });

  it('handles empty layer array gracefully', () => {
    const gcode = layersToGcode([], {});
    assert.match(gcode, /^; Generated by 3DPrintForge/);
    assert.match(gcode, /M84/);
  });
});

describe('native-slicer: sliceMeshToGcode end-to-end', () => {
  it('slices a 10mm cube into 50 layers at 0.2 mm height', async () => {
    const cube = box(10, 10, 10);
    const result = await sliceMeshToGcode(cube, { layerHeight: 0.2 });
    assert.equal(result.layers, 50);
    assert.ok(result.gcode.length > 1000, 'should produce substantial gcode');
    assert.match(result.gcode, /; --- layer 1\/50/);
    assert.match(result.gcode, /; --- layer 50\/50/);
  });

  it('respects custom layer height', async () => {
    const cube = box(10, 10, 10);
    const result = await sliceMeshToGcode(cube, { layerHeight: 0.4 });
    assert.equal(result.layers, 25);
  });
});

describe('native-slicer: helpers', () => {
  it('_signedArea is positive for CCW polygon', () => {
    const ccw = [[0, 0], [10, 0], [10, 10], [0, 10]];
    assert.ok(_internals._signedArea(ccw) > 0);
  });

  it('_signedArea is negative for CW polygon', () => {
    const cw = [[0, 0], [0, 10], [10, 10], [10, 0]];
    assert.ok(_internals._signedArea(cw) < 0);
  });

  it('_near matches points within EPS tolerance', () => {
    assert.equal(_internals._near([0, 0], [0.0005, 0.0005]), true);
    assert.equal(_internals._near([0, 0], [0.5, 0.5]), false);
  });
});

describe('native-slicer: pressure advance & patterns', () => {
  it('emits M900 K for Marlin pressure advance', async () => {
    const r = await sliceMeshToGcode(box(16, 16, 6), { pressureAdvance: 0.035, supports: false });
    assert.match(r.gcode, /M900 K0\.0350/);
  });
  it('emits SET_PRESSURE_ADVANCE for Klipper flavor', async () => {
    const r = await sliceMeshToGcode(box(16, 16, 6), { pressureAdvance: 0.04, gcodeFlavor: 'klipper', supports: false });
    assert.match(r.gcode, /SET_PRESSURE_ADVANCE ADVANCE=0\.0400/);
  });
  it('adaptive layer height uses fewer layers on a vertical-walled cube', async () => {
    const uni = await sliceMeshToGcode(box(20, 20, 20), { layerHeight: 0.2, supports: false });
    const ada = await sliceMeshToGcode(box(20, 20, 20), { layerHeight: 0.2, adaptiveLayers: true, minLayerHeight: 0.08, maxLayerHeight: 0.3, supports: false });
    assert.ok(ada.layers < uni.layers, `adaptive ${ada.layers} should be < uniform ${uni.layers}`);
    const zs = [...ada.gcode.matchAll(/;Z:([\d.]+)/g)].map((m) => +m[1]);
    for (let i = 1; i < zs.length; i++) assert.ok(zs[i] > zs[i - 1], 'adaptive Z stays monotonic');
    assert.ok(!ada.gcode.includes('NaN'));
  });
  it('arachne wall generator varies thin-feature fill but is byte-identical when off', async () => {
    const off = await sliceMeshToGcode(cylinder(8, 15), { supports: false });
    const classic = await sliceMeshToGcode(cylinder(8, 15), { supports: false, wallGenerator: 'classic' });
    assert.equal(classic.gcode, off.gcode, 'classic must equal the default');
    const arachne = await sliceMeshToGcode(cylinder(8, 15), { supports: false, wallGenerator: 'arachne' });
    assert.notEqual(arachne.gcode, classic.gcode, 'arachne must vary the thin-feature fill');
    assert.ok(!arachne.gcode.includes('NaN'));
  });
  it('lightning infill uses less material than grid (hollow interior)', async () => {
    const grid = await sliceMeshToGcode(box(30, 30, 20), { supports: false, infillPattern: 'grid', infillDensity: 0.15 });
    const light = await sliceMeshToGcode(box(30, 30, 20), { supports: false, infillPattern: 'lightning', infillDensity: 0.15 });
    assert.ok(light.gcode.length < grid.gcode.length, `lightning ${light.gcode.length} should be < grid ${grid.gcode.length}`);
    assert.ok(!light.gcode.includes('NaN'));
    assert.equal(light.layers, grid.layers);
  });
  it('scarf seam changes the outer wall but is byte-identical when off', async () => {
    const off = await sliceMeshToGcode(box(20, 20, 10), { supports: false, scarfSeam: false });
    const off2 = await sliceMeshToGcode(box(20, 20, 10), { supports: false });
    assert.equal(off.gcode, off2.gcode, 'scarf off must not change anything');
    const on = await sliceMeshToGcode(box(20, 20, 10), { supports: false, scarfSeam: true, scarfLength: 5 });
    assert.notEqual(on.gcode, off.gcode, 'scarf on must taper the seam');
    assert.ok(!on.gcode.includes('NaN'));
  });
  it('fuzzy-skin painting fuzzes only inside a band, leaving the rest clean', async () => {
    const plain = await sliceMeshToGcode(box(20, 20, 10), { supports: false, fuzzySkin: false });
    const away = await sliceMeshToGcode(box(20, 20, 10), { supports: false, fuzzyPaint: { enforce: [[500, 500, 501, 500, 500, 501, -1000, 1000]] } });
    const full = await sliceMeshToGcode(box(20, 20, 10), { supports: false, fuzzyPaint: { enforce: [[-1000, -1000, 1000, -1000, 1000, 1000, -1000, 1000]] } });
    assert.equal(away.gcode.length, plain.gcode.length, 'a band away from the model leaves walls untouched');
    assert.ok(full.gcode.length > plain.gcode.length * 2, 'a full-coverage band fuzzes the whole outline');
  });
  it('crosshatch infill flips direction between layer bands', () => {
    const sq = { outer: [[0, 0], [40, 0], [40, 40], [0, 40]], holes: [] };
    const a = patternInfill(sq, 0.2, 0, 0.4, 'crosshatch', { z: 1 });
    const b = patternInfill(sq, 0.2, 0, 0.4, 'crosshatch', { z: 3 });
    assert.ok(a.length && b.length);
    assert.notDeepEqual(a[0], b[0]);
  });
});

describe('native-slicer: seam painting', () => {
  const SQ = [[0, 0], [10, 0], [10, 10], [0, 10]];
  it("'back' seam starts at a rear (max-y) vertex", () => {
    assert.equal(seamStart(SQ, 'back')[0][1], 10);
  });
  it('an enforced band snaps the seam into it', () => {
    const enforce = [[-1, -1, 3, -1, -1, 3, 0, 10]];   // covers the (0,0) corner
    assert.deepEqual(seamStart(SQ, 'back', { enforce, block: [], z: 5 })[0], [0, 0]);
  });
  it('a blocked band nudges the seam away', () => {
    const block = [[8, 8, 12, 8, 10, 12, 0, 10]];      // covers (10,10), the 'back' pick
    assert.notDeepEqual(seamStart(SQ, 'back', { enforce: [], block, z: 5 })[0], [10, 10]);
  });
  it('a band outside the layer z-range is ignored', () => {
    const enforce = [[-1, -1, 3, -1, -1, 3, 0, 10]];
    assert.equal(seamStart(SQ, 'back', { enforce, block: [], z: 50 })[0][1], 10);
  });
});

describe('native-slicer: brim_type', () => {
  const cube = box(20, 20, 20);
  // Count extruding moves emitted under the brim feature (robust vs the
  // FEATURE comment, which only prints on a feature change).
  const brimLines = (g) => {
    let inBrim = false, n = 0;
    for (const ln of g.split('\n')) {
      if (ln.startsWith('; FEATURE:')) { inBrim = ln.includes('FEATURE:brim'); continue; }
      if (inBrim && ln.startsWith('G1') && ln.includes('X') && ln.includes('E')) n++;
    }
    return n;
  };

  it('outer_only generates concentric brim loops around the part', async () => {
    const { gcode } = await sliceMeshToGcode(cube, { layerHeight: 0.2, brimWidth: 2, brimType: 'outer_only', supports: false });
    assert.ok(brimLines(gcode) >= 3, `expected several brim moves, got ${brimLines(gcode)}`);
  });

  it('no_brim emits no brim even when a width is set', async () => {
    const { gcode } = await sliceMeshToGcode(cube, { layerHeight: 0.2, brimWidth: 2, brimType: 'no_brim', supports: false });
    assert.equal(brimLines(gcode), 0, 'no_brim must fully disable the brim');
  });

  it('brim_ears attaches discs at sharp corners but skips smooth outlines', async () => {
    // A cube has 4 sharp (90°) convex corners → ears appear.
    const cubeEars = (await sliceMeshToGcode(cube, { layerHeight: 0.2, brimWidth: 2, brimType: 'brim_ears', supports: false })).gcode;
    assert.ok(brimLines(cubeEars) > 0, 'a cube must get corner ears');
    // A cylinder has no sharp corners → no ears (correct, unlike a full brim).
    const cyl = cylinder(10, 20, 48);
    const cylEars = (await sliceMeshToGcode(cyl, { layerHeight: 0.2, brimWidth: 2, brimType: 'brim_ears', supports: false })).gcode;
    assert.equal(brimLines(cylEars), 0, 'a smooth cylinder must get no ears');
    // …but a full outer brim would still wrap the cylinder.
    const cylOuter = (await sliceMeshToGcode(cyl, { layerHeight: 0.2, brimWidth: 2, brimType: 'outer_only', supports: false })).gcode;
    assert.ok(brimLines(cylOuter) > 0, 'outer_only still brims a cylinder');
  });
});

describe('native-slicer: raft', () => {
  const cube = box(20, 20, 20);
  const firstObjectZ = (g) => {
    // The lowest wall Z = where the object starts (above any raft).
    let feat = '', z = null;
    for (const ln of g.split('\n')) {
      if (ln.startsWith('; FEATURE:')) { feat = ln.slice(10).trim(); continue; }
      const m = ln.match(/^; --- layer \d+\/\d+ z=([\d.]+)/);
      if (m) z = parseFloat(m[1]);
      if (feat.includes('wall') && z != null) return z;
    }
    return null;
  };

  it('raft_layers adds base layers and lifts the object', async () => {
    const none = await sliceMeshToGcode(cube, { layerHeight: 0.2, raftLayers: 0, supports: false });
    const rafted = await sliceMeshToGcode(cube, { layerHeight: 0.2, raftLayers: 3, supports: false });
    assert.equal(rafted.layers, none.layers + 3, 'raft adds exactly raftLayers layers');
    const zNone = firstObjectZ(none.gcode), zRaft = firstObjectZ(rafted.gcode);
    assert.ok(zRaft > zNone, `object should start higher with a raft (${zRaft} vs ${zNone})`);
    assert.ok(Math.abs(zRaft - zNone - 3 * 0.2) < 1e-6, 'object lifts by exactly raft thickness');
  });

  it('a raft suppresses the object brim (raft is the adhesion)', async () => {
    const { gcode } = await sliceMeshToGcode(cube, { layerHeight: 0.2, raftLayers: 2, brimWidth: 4, brimType: 'outer_only', supports: false });
    assert.ok(!/; FEATURE:brim/.test(gcode), 'no brim when a raft is present');
  });
});
