// native-slicer.test.js — Verify the pure-JS slicer pipeline produces
// valid layer polygons + reasonable G-code for simple shapes.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import {
  sliceLayer, offsetPolygon, lineInfill, layersToGcode, sliceMeshToGcode, _internals,
} from '../../server/native-slicer.js';
import { box, cylinder } from '../../server/mesh-primitives.js';

describe('native-slicer: sliceLayer', () => {
  it('a 10mm cube cut at z=5 yields one square polygon', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, 5);
    assert.ok(polys.length >= 1, 'at least one polygon');
    // Square outline — 4 corners + up to 4 midpoint vertices from
    // diagonal edges of split-quad faces (8 total). Still a square.
    const total = polys[0].length;
    assert.ok(total >= 4 && total <= 12, `expected 4-12 vertices, got ${total}`);
    // Verify it spans the full 10×10 outline.
    const xs = polys[0].map(p => p[0]);
    const ys = polys[0].map(p => p[1]);
    assert.equal(Math.min(...xs), 0);
    assert.equal(Math.max(...xs), 10);
    assert.equal(Math.min(...ys), 0);
    assert.equal(Math.max(...ys), 10);
  });

  it('cube cut above its top z returns empty', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, 12);
    assert.equal(polys.length, 0);
  });

  it('cube cut below its bottom z returns empty', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, -1);
    assert.equal(polys.length, 0);
  });

  it('cylinder cut at mid-height yields a many-vertex polygon', () => {
    const cyl = cylinder(10, 20, 32);
    const polys = sliceLayer(cyl, 10);
    assert.ok(polys.length >= 1);
    assert.ok(polys[0].length > 16, `cylinder polygon should have many vertices, got ${polys[0].length}`);
  });
});

describe('native-slicer: offsetPolygon', () => {
  it('shrinking a square by 1 produces a smaller square', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const inner = offsetPolygon(square, -1);
    assert.equal(inner.length, 4);
    // Each corner moves inward by ~1 unit along the bisector.
    const minX = Math.min(...inner.map(p => p[0]));
    const maxX = Math.max(...inner.map(p => p[0]));
    assert.ok(Math.abs(minX - 1) < 0.1, `inner left should be ~1, got ${minX}`);
    assert.ok(Math.abs(maxX - 9) < 0.1, `inner right should be ~9, got ${maxX}`);
  });

  it('growing a square by 1 produces a larger square', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const outer = offsetPolygon(square, 1);
    assert.equal(outer.length, 4);
    const minX = Math.min(...outer.map(p => p[0]));
    const maxX = Math.max(...outer.map(p => p[0]));
    assert.ok(minX < -0.5 && maxX > 10.5);
  });

  it('returns empty for degenerate (over-shrunk) polygon', () => {
    const tinySquare = [[0, 0], [2, 0], [2, 2], [0, 2]];
    const inner = offsetPolygon(tinySquare, -10);
    assert.deepEqual(inner, []);
  });
});

describe('native-slicer: lineInfill', () => {
  it('generates parallel hatching segments inside a square', () => {
    const square = [[0, 0], [20, 0], [20, 20], [0, 20]];
    const segs = lineInfill(square, 0.3, 45, 0.4);
    assert.ok(segs.length > 0);
    // Each segment is two points.
    for (const s of segs) {
      assert.equal(s.length, 2);
      assert.equal(s[0].length, 2);
    }
  });

  it('zero density returns empty', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const segs = lineInfill(square, 0, 0, 0.4);
    assert.deepEqual(segs, []);
  });
});

describe('native-slicer: layersToGcode', () => {
  it('emits valid G-code skeleton with header + finisher', () => {
    const layers = [
      { perimeters: [[[0, 0], [10, 0], [10, 10], [0, 10]]], infill: [] },
    ];
    const gcode = layersToGcode(layers, { layerHeight: 0.2, nozzleTemp: 210, bedTemp: 60 });
    assert.match(gcode, /M104 S210/);
    assert.match(gcode, /M140 S60/);
    assert.match(gcode, /G28/);
    assert.match(gcode, /G1 X10\.000 Y0\.000/);   // perimeter move
    assert.match(gcode, /M104 S0/);               // cooldown
    assert.match(gcode, /M84/);                   // motors off
  });

  it('handles empty layer array gracefully', () => {
    const gcode = layersToGcode([], {});
    assert.match(gcode, /^; Generated by 3DPrintForge/);
    assert.match(gcode, /M84/);
  });
});

describe('native-slicer: sliceMeshToGcode end-to-end', () => {
  it('slices a 10mm cube into 50 layers at 0.2 mm height', async () => {
    const cube = box(10, 10, 10);
    const result = await sliceMeshToGcode(cube, { layerHeight: 0.2 });
    assert.equal(result.layers, 50);
    assert.ok(result.gcode.length > 1000, 'should produce substantial gcode');
    assert.match(result.gcode, /; --- layer 1\/50/);
    assert.match(result.gcode, /; --- layer 50\/50/);
  });

  it('respects custom layer height', async () => {
    const cube = box(10, 10, 10);
    const result = await sliceMeshToGcode(cube, { layerHeight: 0.4 });
    assert.equal(result.layers, 25);
  });
});

describe('native-slicer: helpers', () => {
  it('_signedArea is positive for CCW polygon', () => {
    const ccw = [[0, 0], [10, 0], [10, 10], [0, 10]];
    assert.ok(_internals._signedArea(ccw) > 0);
  });

  it('_signedArea is negative for CW polygon', () => {
    const cw = [[0, 0], [0, 10], [10, 10], [10, 0]];
    assert.ok(_internals._signedArea(cw) < 0);
  });

  it('_near matches points within EPS tolerance', () => {
    assert.equal(_internals._near([0, 0], [0.0005, 0.0005]), true);
    assert.equal(_internals._near([0, 0], [0.5, 0.5]), false);
  });
});
