// native-slicer.test.js — Verify the pure-JS slicer pipeline produces
// valid layer polygons + reasonable G-code for simple shapes.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import {
  sliceLayer, offsetPolygon, lineInfill, layersToGcode, sliceMeshToGcode, seamStart, _internals,
} from '../../server/native-slicer.js';
import { patternInfill } from '../../server/native-slicer-geo.js';
import { box, cylinder } from '../../server/mesh-primitives.js';

describe('native-slicer: sliceLayer', () => {
  it('a 10mm cube cut at z=5 yields one square polygon', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, 5);
    assert.ok(polys.length >= 1, 'at least one polygon');
    // Square outline — 4 corners + up to 4 midpoint vertices from
    // diagonal edges of split-quad faces (8 total). Still a square.
    const total = polys[0].length;
    assert.ok(total >= 4 && total <= 12, `expected 4-12 vertices, got ${total}`);
    // Verify it spans the full 10×10 outline.
    const xs = polys[0].map(p => p[0]);
    const ys = polys[0].map(p => p[1]);
    assert.equal(Math.min(...xs), 0);
    assert.equal(Math.max(...xs), 10);
    assert.equal(Math.min(...ys), 0);
    assert.equal(Math.max(...ys), 10);
  });

  it('cube cut above its top z returns empty', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, 12);
    assert.equal(polys.length, 0);
  });

  it('cube cut below its bottom z returns empty', () => {
    const cube = box(10, 10, 10);
    const polys = sliceLayer(cube, -1);
    assert.equal(polys.length, 0);
  });

  it('cylinder cut at mid-height yields a many-vertex polygon', () => {
    const cyl = cylinder(10, 20, 32);
    const polys = sliceLayer(cyl, 10);
    assert.ok(polys.length >= 1);
    assert.ok(polys[0].length > 16, `cylinder polygon should have many vertices, got ${polys[0].length}`);
  });
});

describe('native-slicer: offsetPolygon', () => {
  it('shrinking a square by 1 produces a smaller square', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const inner = offsetPolygon(square, -1);
    assert.equal(inner.length, 4);
    // Each corner moves inward by ~1 unit along the bisector.
    const minX = Math.min(...inner.map(p => p[0]));
    const maxX = Math.max(...inner.map(p => p[0]));
    assert.ok(Math.abs(minX - 1) < 0.1, `inner left should be ~1, got ${minX}`);
    assert.ok(Math.abs(maxX - 9) < 0.1, `inner right should be ~9, got ${maxX}`);
  });

  it('growing a square by 1 produces a larger square', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const outer = offsetPolygon(square, 1);
    assert.equal(outer.length, 4);
    const minX = Math.min(...outer.map(p => p[0]));
    const maxX = Math.max(...outer.map(p => p[0]));
    assert.ok(minX < -0.5 && maxX > 10.5);
  });

  it('returns empty for degenerate (over-shrunk) polygon', () => {
    const tinySquare = [[0, 0], [2, 0], [2, 2], [0, 2]];
    const inner = offsetPolygon(tinySquare, -10);
    assert.deepEqual(inner, []);
  });
});

describe('native-slicer: lineInfill', () => {
  it('generates parallel hatching segments inside a square', () => {
    const square = [[0, 0], [20, 0], [20, 20], [0, 20]];
    const segs = lineInfill(square, 0.3, 45, 0.4);
    assert.ok(segs.length > 0);
    // Each segment is two points.
    for (const s of segs) {
      assert.equal(s.length, 2);
      assert.equal(s[0].length, 2);
    }
  });

  it('zero density returns empty', () => {
    const square = [[0, 0], [10, 0], [10, 10], [0, 10]];
    const segs = lineInfill(square, 0, 0, 0.4);
    assert.deepEqual(segs, []);
  });
});

describe('native-slicer: layersToGcode', () => {
  it('emits valid G-code skeleton with header + finisher', () => {
    const layers = [
      { perimeters: [[[0, 0], [10, 0], [10, 10], [0, 10]]], infill: [] },
    ];
    const gcode = layersToGcode(layers, { layerHeight: 0.2, nozzleTemp: 210, bedTemp: 60 });
    assert.match(gcode, /M104 S210/);
    assert.match(gcode, /M140 S60/);
    assert.match(gcode, /G28/);
    assert.match(gcode, /G1 X10\.000 Y0\.000/);   // perimeter move
    assert.match(gcode, /M104 S0/);               // cooldown
    assert.match(gcode, /M84/);                   // motors off
  });

  it('handles empty layer array gracefully', () => {
    const gcode = layersToGcode([], {});
    assert.match(gcode, /^; Generated by 3DPrintForge/);
    assert.match(gcode, /M84/);
  });
});

describe('native-slicer: sliceMeshToGcode end-to-end', () => {
  it('slices a 10mm cube into 50 layers at 0.2 mm height', async () => {
    const cube = box(10, 10, 10);
    const result = await sliceMeshToGcode(cube, { layerHeight: 0.2 });
    assert.equal(result.layers, 50);
    assert.ok(result.gcode.length > 1000, 'should produce substantial gcode');
    assert.match(result.gcode, /; --- layer 1\/50/);
    assert.match(result.gcode, /; --- layer 50\/50/);
  });

  it('respects custom layer height', async () => {
    const cube = box(10, 10, 10);
    const result = await sliceMeshToGcode(cube, { layerHeight: 0.4 });
    assert.equal(result.layers, 25);
  });
});

describe('native-slicer: helpers', () => {
  it('_signedArea is positive for CCW polygon', () => {
    const ccw = [[0, 0], [10, 0], [10, 10], [0, 10]];
    assert.ok(_internals._signedArea(ccw) > 0);
  });

  it('_signedArea is negative for CW polygon', () => {
    const cw = [[0, 0], [0, 10], [10, 10], [10, 0]];
    assert.ok(_internals._signedArea(cw) < 0);
  });

  it('_near matches points within EPS tolerance', () => {
    assert.equal(_internals._near([0, 0], [0.0005, 0.0005]), true);
    assert.equal(_internals._near([0, 0], [0.5, 0.5]), false);
  });
});

describe('native-slicer: pressure advance & patterns', () => {
  it('emits M900 K for Marlin pressure advance', async () => {
    const r = await sliceMeshToGcode(box(16, 16, 6), { pressureAdvance: 0.035, supports: false });
    assert.match(r.gcode, /M900 K0\.0350/);
  });
  it('emits SET_PRESSURE_ADVANCE for Klipper flavor', async () => {
    const r = await sliceMeshToGcode(box(16, 16, 6), { pressureAdvance: 0.04, gcodeFlavor: 'klipper', supports: false });
    assert.match(r.gcode, /SET_PRESSURE_ADVANCE ADVANCE=0\.0400/);
  });
  it('adaptive layer height uses fewer layers on a vertical-walled cube', async () => {
    const uni = await sliceMeshToGcode(box(20, 20, 20), { layerHeight: 0.2, supports: false });
    const ada = await sliceMeshToGcode(box(20, 20, 20), { layerHeight: 0.2, adaptiveLayers: true, minLayerHeight: 0.08, maxLayerHeight: 0.3, supports: false });
    assert.ok(ada.layers < uni.layers, `adaptive ${ada.layers} should be < uniform ${uni.layers}`);
    const zs = [...ada.gcode.matchAll(/;Z:([\d.]+)/g)].map((m) => +m[1]);
    for (let i = 1; i < zs.length; i++) assert.ok(zs[i] > zs[i - 1], 'adaptive Z stays monotonic');
    assert.ok(!ada.gcode.includes('NaN'));
  });
  it('arachne wall generator varies thin-feature fill but is byte-identical when off', async () => {
    const off = await sliceMeshToGcode(cylinder(8, 15), { supports: false });
    const classic = await sliceMeshToGcode(cylinder(8, 15), { supports: false, wallGenerator: 'classic' });
    assert.equal(classic.gcode, off.gcode, 'classic must equal the default');
    const arachne = await sliceMeshToGcode(cylinder(8, 15), { supports: false, wallGenerator: 'arachne' });
    assert.notEqual(arachne.gcode, classic.gcode, 'arachne must vary the thin-feature fill');
    assert.ok(!arachne.gcode.includes('NaN'));
  });
  it('lightning infill uses less material than grid (hollow interior)', async () => {
    const grid = await sliceMeshToGcode(box(30, 30, 20), { supports: false, infillPattern: 'grid', infillDensity: 0.15 });
    const light = await sliceMeshToGcode(box(30, 30, 20), { supports: false, infillPattern: 'lightning', infillDensity: 0.15 });
    assert.ok(light.gcode.length < grid.gcode.length, `lightning ${light.gcode.length} should be < grid ${grid.gcode.length}`);
    assert.ok(!light.gcode.includes('NaN'));
    assert.equal(light.layers, grid.layers);
  });
  it('scarf seam changes the outer wall but is byte-identical when off', async () => {
    const off = await sliceMeshToGcode(box(20, 20, 10), { supports: false, scarfSeam: false });
    const off2 = await sliceMeshToGcode(box(20, 20, 10), { supports: false });
    assert.equal(off.gcode, off2.gcode, 'scarf off must not change anything');
    const on = await sliceMeshToGcode(box(20, 20, 10), { supports: false, scarfSeam: true, scarfLength: 5 });
    assert.notEqual(on.gcode, off.gcode, 'scarf on must taper the seam');
    assert.ok(!on.gcode.includes('NaN'));
  });
  it('fuzzy-skin painting fuzzes only inside a band, leaving the rest clean', async () => {
    const plain = await sliceMeshToGcode(box(20, 20, 10), { supports: false, fuzzySkin: false });
    const away = await sliceMeshToGcode(box(20, 20, 10), { supports: false, fuzzyPaint: { enforce: [[500, 500, 501, 500, 500, 501, -1000, 1000]] } });
    const full = await sliceMeshToGcode(box(20, 20, 10), { supports: false, fuzzyPaint: { enforce: [[-1000, -1000, 1000, -1000, 1000, 1000, -1000, 1000]] } });
    assert.equal(away.gcode.length, plain.gcode.length, 'a band away from the model leaves walls untouched');
    assert.ok(full.gcode.length > plain.gcode.length * 2, 'a full-coverage band fuzzes the whole outline');
  });
  it('crosshatch infill flips direction between layer bands', () => {
    const sq = { outer: [[0, 0], [40, 0], [40, 40], [0, 40]], holes: [] };
    const a = patternInfill(sq, 0.2, 0, 0.4, 'crosshatch', { z: 1 });
    const b = patternInfill(sq, 0.2, 0, 0.4, 'crosshatch', { z: 3 });
    assert.ok(a.length && b.length);
    assert.notDeepEqual(a[0], b[0]);
  });
});

describe('native-slicer: seam painting', () => {
  const SQ = [[0, 0], [10, 0], [10, 10], [0, 10]];
  it("'back' seam starts at a rear (max-y) vertex", () => {
    assert.equal(seamStart(SQ, 'back')[0][1], 10);
  });
  it('an enforced band snaps the seam into it', () => {
    const enforce = [[-1, -1, 3, -1, -1, 3, 0, 10]];   // covers the (0,0) corner
    assert.deepEqual(seamStart(SQ, 'back', { enforce, block: [], z: 5 })[0], [0, 0]);
  });
  it('a blocked band nudges the seam away', () => {
    const block = [[8, 8, 12, 8, 10, 12, 0, 10]];      // covers (10,10), the 'back' pick
    assert.notDeepEqual(seamStart(SQ, 'back', { enforce: [], block, z: 5 })[0], [10, 10]);
  });
  it('a band outside the layer z-range is ignored', () => {
    const enforce = [[-1, -1, 3, -1, -1, 3, 0, 10]];
    assert.equal(seamStart(SQ, 'back', { enforce, block: [], z: 50 })[0][1], 10);
  });
});

describe('native-slicer: brim_type', () => {
  const cube = box(20, 20, 20);
  // Count extruding moves emitted under the brim feature (robust vs the
  // FEATURE comment, which only prints on a feature change).
  const brimLines = (g) => {
    let inBrim = false, n = 0;
    for (const ln of g.split('\n')) {
      if (ln.startsWith('; FEATURE:')) { inBrim = ln.includes('FEATURE:brim'); continue; }
      if (inBrim && ln.startsWith('G1') && ln.includes('X') && ln.includes('E')) n++;
    }
    return n;
  };

  it('outer_only generates concentric brim loops around the part', async () => {
    const { gcode } = await sliceMeshToGcode(cube, { layerHeight: 0.2, brimWidth: 2, brimType: 'outer_only', supports: false });
    assert.ok(brimLines(gcode) >= 3, `expected several brim moves, got ${brimLines(gcode)}`);
  });

  it('no_brim emits no brim even when a width is set', async () => {
    const { gcode } = await sliceMeshToGcode(cube, { layerHeight: 0.2, brimWidth: 2, brimType: 'no_brim', supports: false });
    assert.equal(brimLines(gcode), 0, 'no_brim must fully disable the brim');
  });

  it('brim_ears attaches discs at sharp corners but skips smooth outlines', async () => {
    // A cube has 4 sharp (90°) convex corners → ears appear.
    const cubeEars = (await sliceMeshToGcode(cube, { layerHeight: 0.2, brimWidth: 2, brimType: 'brim_ears', supports: false })).gcode;
    assert.ok(brimLines(cubeEars) > 0, 'a cube must get corner ears');
    // A cylinder has no sharp corners → no ears (correct, unlike a full brim).
    const cyl = cylinder(10, 20, 48);
    const cylEars = (await sliceMeshToGcode(cyl, { layerHeight: 0.2, brimWidth: 2, brimType: 'brim_ears', supports: false })).gcode;
    assert.equal(brimLines(cylEars), 0, 'a smooth cylinder must get no ears');
    // …but a full outer brim would still wrap the cylinder.
    const cylOuter = (await sliceMeshToGcode(cyl, { layerHeight: 0.2, brimWidth: 2, brimType: 'outer_only', supports: false })).gcode;
    assert.ok(brimLines(cylOuter) > 0, 'outer_only still brims a cylinder');
  });
});

describe('native-slicer: raft', () => {
  const cube = box(20, 20, 20);
  const firstObjectZ = (g) => {
    // The lowest wall Z = where the object starts (above any raft).
    let feat = '', z = null;
    for (const ln of g.split('\n')) {
      if (ln.startsWith('; FEATURE:')) { feat = ln.slice(10).trim(); continue; }
      const m = ln.match(/^; --- layer \d+\/\d+ z=([\d.]+)/);
      if (m) z = parseFloat(m[1]);
      if (feat.includes('wall') && z != null) return z;
    }
    return null;
  };

  it('raft_layers adds base layers and lifts the object', async () => {
    const none = await sliceMeshToGcode(cube, { layerHeight: 0.2, raftLayers: 0, supports: false });
    const rafted = await sliceMeshToGcode(cube, { layerHeight: 0.2, raftLayers: 3, supports: false });
    assert.equal(rafted.layers, none.layers + 3, 'raft adds exactly raftLayers layers');
    const zNone = firstObjectZ(none.gcode), zRaft = firstObjectZ(rafted.gcode);
    assert.ok(zRaft > zNone, `object should start higher with a raft (${zRaft} vs ${zNone})`);
    assert.ok(Math.abs(zRaft - zNone - 3 * 0.2) < 1e-6, 'object lifts by exactly raft thickness');
  });

  it('a raft suppresses the object brim (raft is the adhesion)', async () => {
    const { gcode } = await sliceMeshToGcode(cube, { layerHeight: 0.2, raftLayers: 2, brimWidth: 4, brimType: 'outer_only', supports: false });
    assert.ok(!/; FEATURE:brim/.test(gcode), 'no brim when a raft is present');
  });
});

describe('native-slicer: modifier volumes', () => {
  const slab = box(40, 40, 6);
  const sparseMoves = (g) => {
    let inF = false, n = 0;
    for (const ln of g.split('\n')) {
      if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:sparse'); continue; }
      if (inF && ln.startsWith('G1') && ln.includes('X') && ln.includes('E')) n++;
    }
    return n;
  };

  it('a high-density modifier over half the model adds infill there', async () => {
    const base = await sliceMeshToGcode(slab, { layerHeight: 0.3, infillDensity: 0.08, supports: false });
    const mod = await sliceMeshToGcode(slab, { layerHeight: 0.3, infillDensity: 0.08, supports: false,
      modifiers: [{ box: [0, 0, 0, 20, 40, 6], infillDensity: 0.9 }] });
    assert.ok(sparseMoves(mod.gcode) > sparseMoves(base.gcode) * 1.3, `modifier should densify infill: base=${sparseMoves(base.gcode)} mod=${sparseMoves(mod.gcode)}`);
    assert.ok(!mod.gcode.includes('NaN'));
  });

  it('is byte-identical to no-modifier when the modifiers list is empty', async () => {
    const a = await sliceMeshToGcode(slab, { layerHeight: 0.3, infillDensity: 0.15, supports: false });
    const b = await sliceMeshToGcode(slab, { layerHeight: 0.3, infillDensity: 0.15, supports: false, modifiers: [] });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: manual colour changes', () => {
  it('emits M600 at the chosen 1-based layers', async () => {
    const r = await sliceMeshToGcode(box(20, 20, 10), { layerHeight: 0.2, supports: false, colorChangeLayers: [10, 25] });
    assert.equal((r.gcode.match(/^M600$/gm) || []).length, 2, 'one M600 per colour change');
    assert.match(r.gcode, /; COLOR_CHANGE L10/);
    assert.match(r.gcode, /; COLOR_CHANGE L25/);
  });
  it('emits no M600 without colour changes', async () => {
    const r = await sliceMeshToGcode(box(20, 20, 10), { layerHeight: 0.2, supports: false });
    assert.ok(!r.gcode.includes('M600'));
  });
});

import { sliceMultiMaterialGcode } from '../../server/native-slicer-multi.js';
describe('native-slicer: wipe/prime tower', () => {
  const twoColour = () => [{ ...box(20, 20, 6), extruder: 1 }, { ...box(20, 20, 6), extruder: 2 }];
  it('prints a per-extruder wipe tower when enabled', async () => {
    const r = await sliceMultiMaterialGcode(twoColour(), { layerHeight: 0.3, wipeTower: true, wipeTowerWidth: 24, wipeTowerDepth: 24 });
    assert.ok(r.gcode.includes('; FEATURE:wipe_tower'), 'tower feature present');
    assert.ok((r.gcode.match(/; WIPE_TOWER/g) || []).length >= 2, 'at least one tower band per extruder');
    assert.ok(!r.gcode.includes('NaN'));
  });
  it('prints no tower when disabled', async () => {
    const r = await sliceMultiMaterialGcode(twoColour(), { layerHeight: 0.3, wipeTower: false });
    assert.ok(!r.gcode.includes('WIPE_TOWER'));
  });
});

import { sliceObjectsGcode } from '../../server/native-slicer.js';
describe('native-slicer: sequential (by-object) printing', () => {
  const objs = () => [
    { mesh: box(12, 12, 4), settings: {} },
    { mesh: box(12, 12, 8), settings: {} },
  ];
  it('by_object prints objects sequentially with an OBJECT_CHANGE hop', async () => {
    const r = await sliceObjectsGcode(objs(), { layerHeight: 0.2, printSequence: 'by_object', supports: false });
    assert.ok(r.sequential, 'flagged sequential');
    assert.equal((r.gcode.match(/; OBJECT_CHANGE/g) || []).length, 1, 'one object change for two objects');
    // Object 1 is 4mm (20 layers), object 2 is 8mm (40 layers) -> 60 combined layers.
    assert.equal(r.layers, 60);
    assert.ok(!r.gcode.includes('NaN'));
  });
  it('by_layer (default) interleaves and has no object change', async () => {
    const r = await sliceObjectsGcode(objs(), { layerHeight: 0.2, supports: false });
    assert.ok(!r.sequential);
    assert.ok(!r.gcode.includes('OBJECT_CHANGE'));
  });
  it('warns when a not-last object exceeds gantry clearance', async () => {
    const tall = [{ mesh: box(12, 12, 40), settings: {} }, { mesh: box(12, 12, 6), settings: {} }];
    const r = await sliceObjectsGcode(tall, { layerHeight: 0.3, printSequence: 'by_object', extruderClearanceHeight: 25, supports: false });
    assert.ok(r.warnings.length >= 1, 'a clearance warning is returned');
  });
});

describe('native-slicer: variable layer height bands', () => {
  it('a thin band over part of the model adds layers vs uniform', async () => {
    const uni = await sliceMeshToGcode(box(20, 20, 10), { layerHeight: 0.3, supports: false });
    // Bottom 5mm at 0.1mm (fine), rest at default 0.3mm.
    const varh = await sliceMeshToGcode(box(20, 20, 10), { layerHeight: 0.3, supports: false, layerHeightBands: [{ z0: 0, z1: 5, h: 0.1 }] });
    assert.ok(varh.layers > uni.layers, `variable ${varh.layers} should exceed uniform ${uni.layers}`);
    const zs = [...varh.gcode.matchAll(/;Z:([\d.]+)/g)].map((m) => +m[1]);
    for (let i = 1; i < zs.length; i++) assert.ok(zs[i] > zs[i - 1], 'Z stays monotonic');
    assert.ok(!varh.gcode.includes('NaN'));
  });
  it('is byte-identical to uniform when no bands', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 8), { layerHeight: 0.25, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 8), { layerHeight: 0.25, supports: false, layerHeightBands: [] });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: richer settings batch', () => {
  it('max volumetric speed caps the feedrate', async () => {
    const fast = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, lineWidth: 0.4, outerWallSpeed: 300, innerWallSpeed: 300, sparseInfillSpeed: 300, supports: false });
    const capped = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, lineWidth: 0.4, outerWallSpeed: 300, innerWallSpeed: 300, sparseInfillSpeed: 300, maxVolumetricSpeed: 5, supports: false });
    // Only extruding moves (G1 with E and X) are volumetric-capped; travel isn't.
    const maxF = (g) => Math.max(...g.split('\n').filter((ln) => ln.startsWith('G1') && ln.includes('X') && ln.includes('E')).map((ln) => { const m = ln.match(/F(\d+(?:\.\d+)?)/); return m ? +m[1] : 0; }));
    // cap = 5 mm3/s / (0.4*0.2) = 62.5 mm/s = 3750 mm/min; uncapped hits 300*60=18000.
    assert.ok(maxF(capped.gcode) < maxF(fast.gcode), 'volumetric cap lowers the top feedrate');
    assert.ok(maxF(capped.gcode) <= 3750 + 1, `capped feedrate ~<=3750, got ${maxF(capped.gcode)}`);
  });
  it('fan curve ramps M106 across layers; byte-identical when unset', async () => {
    const flat = await sliceMeshToGcode(box(16, 16, 6), { layerHeight: 0.2, supports: false });
    const flat2 = await sliceMeshToGcode(box(16, 16, 6), { layerHeight: 0.2, supports: false, fanMinSpeed: null, fanMaxSpeed: null });
    assert.equal(flat2.gcode, flat.gcode, 'no curve → identical');
    const ramp = await sliceMeshToGcode(box(16, 16, 6), { layerHeight: 0.2, supports: false, fanMinSpeed: 20, fanMaxSpeed: 100, fullFanSpeedLayer: 20 });
    const fans = [...new Set([...ramp.gcode.matchAll(/M106 S(\d+)/g)].map((m) => +m[1]))];
    assert.ok(fans.length > 2, `fan should take several values, got ${fans.length}`);
  });
  it('min sparse infill area removes infill from a tiny model', async () => {
    const withInfill = await sliceMeshToGcode(box(6, 6, 4), { layerHeight: 0.2, infillDensity: 0.2, supports: false });
    const skipped = await sliceMeshToGcode(box(6, 6, 4), { layerHeight: 0.2, infillDensity: 0.2, minSparseInfillArea: 200, supports: false });
    const sparseMoves = (g) => { let inF = false, n = 0; for (const ln of g.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:sparse'); continue; } if (inF && ln.startsWith('G1') && ln.includes('E')) n++; } return n; };
    assert.ok(sparseMoves(skipped.gcode) < sparseMoves(withInfill.gcode), 'tiny region loses its sparse infill');
  });
});

describe('native-slicer: skirt height', () => {
  const skirtLines = (g) => {
    let inF = false, n = 0;
    for (const ln of g.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:skirt'); continue; } if (inF && ln.startsWith('G1') && ln.includes('X') && ln.includes('E')) n++; }
    return n;
  };
  it('skirt_height prints the skirt on multiple layers', async () => {
    const one = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.3, skirtLoops: 2, supports: false });
    const three = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.3, skirtLoops: 2, skirtHeight: 3, supports: false });
    assert.ok(skirtLines(three.gcode) > skirtLines(one.gcode) * 2, `taller skirt: 1-layer=${skirtLines(one.gcode)} 3-layer=${skirtLines(three.gcode)}`);
  });
  it('default skirt height (1) is byte-identical to before', async () => {
    const a = await sliceMeshToGcode(box(18, 18, 5), { layerHeight: 0.2, skirtLoops: 1, supports: false });
    const b = await sliceMeshToGcode(box(18, 18, 5), { layerHeight: 0.2, skirtLoops: 1, skirtHeight: 1, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: support base pattern + interface spacing', () => {
  // A shape with an overhang so support is actually generated.
  const overhang = box(24, 24, 3);   // thin slab; slice with paint-enforced support
  const supportLines = (g) => { let inF = false, n = 0; for (const ln of g.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:support'); continue; } if (inF && ln.startsWith('G1') && ln.includes('X')) n++; } return n; };
  const enforceAll = [[-20, -20, 20, -20, 0, 20, 100]];   // big enforce triangle over the slab
  it("grid base pattern adds crossing lines vs rectilinear", async () => {
    const rect = await sliceMeshToGcode(overhang, { layerHeight: 0.3, supports: true, supportDensity: 0.15, supportPaint: { enforce: enforceAll, block: [] } });
    const grid = await sliceMeshToGcode(overhang, { layerHeight: 0.3, supports: true, supportDensity: 0.15, supportBasePattern: 'grid', supportPaint: { enforce: enforceAll, block: [] } });
    assert.ok(supportLines(grid.gcode) >= supportLines(rect.gcode), `grid should have >= support lines (rect=${supportLines(rect.gcode)} grid=${supportLines(grid.gcode)})`);
    assert.ok(!grid.gcode.includes('NaN'));
  });
  it('default support (no base pattern) is byte-identical', async () => {
    const a = await sliceMeshToGcode(overhang, { layerHeight: 0.3, supports: true, supportPaint: { enforce: enforceAll, block: [] } });
    const b = await sliceMeshToGcode(overhang, { layerHeight: 0.3, supports: true, supportBasePattern: 'rectilinear', supportPaint: { enforce: enforceAll, block: [] } });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: resolution', () => {
  it('a coarse resolution reduces vertices on a cylinder (smaller g-code)', async () => {
    const fine = await sliceMeshToGcode(cylinder(10, 8, 96), { layerHeight: 0.3, supports: false });
    const coarse = await sliceMeshToGcode(cylinder(10, 8, 96), { layerHeight: 0.3, resolution: 0.5, supports: false });
    const wallMoves = (g) => g.split('\n').filter((ln) => ln.startsWith('G1') && ln.includes('X') && ln.includes('E')).length;
    assert.ok(wallMoves(coarse.gcode) < wallMoves(fine.gcode), `coarse should have fewer moves (fine=${wallMoves(fine.gcode)} coarse=${wallMoves(coarse.gcode)})`);
    assert.ok(!coarse.gcode.includes('NaN'));
  });
  it('resolution 0 is byte-identical to default', async () => {
    const a = await sliceMeshToGcode(cylinder(8, 6, 48), { layerHeight: 0.3, supports: false });
    const b = await sliceMeshToGcode(cylinder(8, 6, 48), { layerHeight: 0.3, resolution: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: top surface speed', () => {
  it('applies a distinct feedrate to the top surface', async () => {
    // 20mm cube, top layers solid. Slow top surface to 20 mm/s.
    const r = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, solidInfillSpeed: 120, topSurfaceSpeed: 20, supports: false });
    // The topmost layers should contain solid moves at F1200 (20*60).
    assert.match(r.gcode, /F1200(\.0+)?\b/);
  });
  it('no top_surface_speed is byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, solidInfillSpeed: 120, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, solidInfillSpeed: 120, topSurfaceSpeed: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: initial layer infill speed + object labels', () => {
  it('initial_layer_infill_speed sets a distinct first-layer infill feedrate', async () => {
    const r = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, firstLayerSpeed: 30, initialLayerInfillSpeed: 10, supports: false });
    assert.match(r.gcode, /F600(\.0+)?\b/, 'first-layer infill at 10 mm/s = F600');
  });
  it('no initial_layer_infill_speed is byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, firstLayerSpeed: 30, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, firstLayerSpeed: 30, initialLayerInfillSpeed: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
  it('gcode_label_objects wraps each object with EXCLUDE_OBJECT markers', async () => {
    const objs = [{ mesh: box(10, 10, 4), settings: {} }, { mesh: box(10, 10, 4), settings: {} }];
    const r = await sliceObjectsGcode(objs, { layerHeight: 0.3, gcodeLabelObjects: true, supports: false });
    assert.ok(r.gcode.includes('EXCLUDE_OBJECT_START NAME=object_1'), 'labels object 1');
    assert.ok(r.gcode.includes('EXCLUDE_OBJECT_START NAME=object_2'), 'labels object 2');
    assert.equal((r.gcode.match(/EXCLUDE_OBJECT_END/g) || []).length, (r.gcode.match(/EXCLUDE_OBJECT_START/g) || []).length, 'balanced start/end');
  });
  it('gcode_label_objects off emits no markers', async () => {
    const r = await sliceObjectsGcode([{ mesh: box(10, 10, 4), settings: {} }, { mesh: box(10, 10, 4), settings: {} }], { layerHeight: 0.3, supports: false });
    assert.ok(!r.gcode.includes('EXCLUDE_OBJECT'));
  });
});

describe('native-slicer: per-feature jerk', () => {
  it('emits distinct M205 values per feature', async () => {
    const r = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, jerk: 9, outerWallJerk: 5, infillJerk: 12, supports: false });
    const jerks = [...new Set([...r.gcode.matchAll(/M205 X(\d+)/g)].map((m) => +m[1]))];
    assert.ok(jerks.includes(5) && jerks.includes(12), `expected 5 and 12 among ${jerks}`);
  });
  it('no per-feature jerk is byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, jerk: 9, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, jerk: 9, outerWallJerk: 0, infillJerk: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: ironing inset + pattern', () => {
  const ironLines = (g) => { let inF = false, n = 0; for (const ln of g.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:ironing'); continue; } if (inF && ln.startsWith('G1') && ln.includes('X')) n++; } return n; };
  it('concentric ironing produces ironing moves', async () => {
    const r = await sliceMeshToGcode(box(24, 24, 4), { layerHeight: 0.2, ironing: true, ironingPattern: 'concentric', supports: false });
    assert.ok(ironLines(r.gcode) > 0, 'concentric ironing emits moves');
    assert.ok(!r.gcode.includes('NaN'));
  });
  it('ironing inset reduces ironing coverage', async () => {
    const none = await sliceMeshToGcode(box(24, 24, 4), { layerHeight: 0.2, ironing: true, supports: false });
    const inset = await sliceMeshToGcode(box(24, 24, 4), { layerHeight: 0.2, ironing: true, ironingInset: 4, supports: false });
    assert.ok(ironLines(inset.gcode) <= ironLines(none.gcode), `inset should not increase ironing (none=${ironLines(none.gcode)} inset=${ironLines(inset.gcode)})`);
  });
  it('default ironing (rectilinear, no inset) byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, ironing: true, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, ironing: true, ironingInset: 0, ironingPattern: 'rectilinear', supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: infill anchor', () => {
  const sparseExtent = (g) => {
    // Total length of sparse EXTRUDE moves — anchoring lengthens each line.
    let inF = false, pos = null, L = 0;
    for (const ln of g.split('\n')) {
      if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:sparse'); continue; }
      const m = ln.match(/^G[01] X([-\d.]+) Y([-\d.]+)/);
      if (!m) continue;
      const p = [+m[1], +m[2]];
      if (inF && ln.startsWith('G1') && /\sE[-\d.]/.test(ln) && pos) L += Math.hypot(p[0] - pos[0], p[1] - pos[1]);
      pos = p;
    }
    return L;
  };
  it('infill_anchor lengthens the sparse infill lines', async () => {
    const none = await sliceMeshToGcode(box(30, 30, 4), { layerHeight: 0.3, infillDensity: 0.2, supports: false });
    const anch = await sliceMeshToGcode(box(30, 30, 4), { layerHeight: 0.3, infillDensity: 0.2, infillAnchor: 0.6, supports: false });
    assert.ok(sparseExtent(anch.gcode) > sparseExtent(none.gcode), `anchored should be longer (none=${sparseExtent(none.gcode).toFixed(0)} anch=${sparseExtent(anch.gcode).toFixed(0)})`);
    assert.ok(!anch.gcode.includes('NaN'));
  });
  it('infill_anchor 0 is byte-identical', async () => {
    const a = await sliceMeshToGcode(box(24, 24, 4), { layerHeight: 0.3, infillDensity: 0.2, supports: false });
    const b = await sliceMeshToGcode(box(24, 24, 4), { layerHeight: 0.3, infillDensity: 0.2, infillAnchor: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: initial layer flow ratio', () => {
  const firstLayerE = (g) => {
    // Sum of positive E deltas on layer 1 (initial layer).
    const l1 = g.split('; --- layer 2/')[0];
    let last = 0, sum = 0;
    for (const m of l1.matchAll(/E(-?\d+\.\d+)/g)) { const e = +m[1]; if (e > last) sum += e - last; last = e; }
    return sum;
  };
  it('initial_layer_flow_ratio raises first-layer extrusion', async () => {
    const base = await sliceMeshToGcode(box(20, 20, 3), { layerHeight: 0.2, supports: false });
    const fat = await sliceMeshToGcode(box(20, 20, 3), { layerHeight: 0.2, initialLayerFlowRatio: 1.3, supports: false });
    assert.ok(firstLayerE(fat.gcode) > firstLayerE(base.gcode) * 1.2, `1.3x flow should raise first-layer E (base=${firstLayerE(base.gcode).toFixed(1)} fat=${firstLayerE(fat.gcode).toFixed(1)})`);
  });
  it('initial_layer_flow_ratio unset byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 3), { layerHeight: 0.2, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 3), { layerHeight: 0.2, initialLayerFlowRatio: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: bridge/support acceleration', () => {
  it('support_acceleration emits its own M204 on support moves', async () => {
    const enforce = [[-20, -20, 20, -20, 0, 20, 100]];
    const r = await sliceMeshToGcode(box(24, 24, 3), { layerHeight: 0.3, acceleration: 5000, outerWallAccel: 3000, supportAccel: 700, supports: true, supportPaint: { enforce, block: [] } });
    const accels = [...new Set([...r.gcode.matchAll(/M204 P(\d+)/g)].map((m) => +m[1]))];
    assert.ok(accels.includes(700), `expected 700 among ${accels}`);
  });
  it('no bridge/support accel is byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, acceleration: 5000, outerWallAccel: 3000, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, acceleration: 5000, outerWallAccel: 3000, bridgeAccel: 0, supportAccel: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: only one wall top', () => {
  const wallMoves = (g, feat) => { let inF = false, n = 0; for (const ln of g.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes(`FEATURE:${feat}`); continue; } if (inF && ln.startsWith('G1') && ln.includes('X') && ln.includes('E')) n++; } return n; };
  it('reduces inner-wall moves on the top surface', async () => {
    const opts = { layerHeight: 0.2, wall_loops: 3, supports: false };
    const normal = await sliceMeshToGcode(box(20, 20, 4), { ...opts, wallLoops: 3 });
    const oneTop = await sliceMeshToGcode(box(20, 20, 4), { ...opts, wallLoops: 3, onlyOneWallTop: true });
    assert.ok(wallMoves(oneTop.gcode, 'inner-wall') < wallMoves(normal.gcode, 'inner-wall'), `top-only should cut inner walls (normal=${wallMoves(normal.gcode, 'inner-wall')} oneTop=${wallMoves(oneTop.gcode, 'inner-wall')})`);
    assert.ok(!oneTop.gcode.includes('NaN'));
  });
  it('only_one_wall_top off is byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, wallLoops: 3, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, wallLoops: 3, onlyOneWallTop: false, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: bottom surface speed', () => {
  it('applies a distinct feedrate to the bottom surface', async () => {
    const r = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, solidInfillSpeed: 120, bottomSurfaceSpeed: 25, supports: false });
    assert.match(r.gcode, /F1500(\.0+)?\b/, 'bottom surface at 25 mm/s = F1500');
  });
  it('no bottom_surface_speed byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, solidInfillSpeed: 120, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, solidInfillSpeed: 120, bottomSurfaceSpeed: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

import { generateSupports } from '../../server/native-slicer-support.js';
describe('native-slicer: support interface tagging', () => {
  it('interface hatch lines are tagged so support_interface_speed can apply', () => {
    // A square that appears only at higher layers (air below) → support with a
    // dense interface just under it.
    const sq = [[0, 0], [20, 0], [20, 20], [0, 20]];
    const layerRegions = [];
    for (let i = 0; i < 12; i++) layerRegions.push(i >= 8 ? [{ outer: sq, holes: [] }] : []);
    const segs = generateSupports(layerRegions, { lineWidth: 0.4, gridRes: 1, density: 0.1, layerHeight: 0.2, interfaceLayers: 2, zGapLayers: 1 });
    const hasIface = segs.some((layer) => layer.some((p) => p.iface === true));
    const hasBase = segs.some((layer) => layer.some((p) => p.iface === false));
    assert.ok(hasIface, 'some interface-tagged support lines exist');
    assert.ok(hasBase, 'some base-tagged support lines exist');
  });
});

describe('native-slicer: first-layer wall loops', () => {
  // Count inner-wall extrude moves within the first layer only.
  const firstLayerInnerMoves = (g) => {
    const l1 = g.split('; --- layer 2/')[0];
    let inF = false, n = 0;
    for (const ln of l1.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes('FEATURE:inner-wall'); continue; } if (inF && ln.startsWith('G1') && ln.includes('X') && ln.includes('E')) n++; }
    return n;
  };
  it('first_layer_wall_loops changes the first-layer perimeter count', async () => {
    const base = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, wallLoops: 2, supports: false });
    const more = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, wallLoops: 2, firstLayerWallLoops: 4, supports: false });
    assert.ok(firstLayerInnerMoves(more.gcode) > firstLayerInnerMoves(base.gcode), `more first-layer walls (base=${firstLayerInnerMoves(base.gcode)} more=${firstLayerInnerMoves(more.gcode)})`);
  });
  it('first_layer_wall_loops unset byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, wallLoops: 2, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, wallLoops: 2, firstLayerWallLoops: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: precise wall', () => {
  it('precise_wall pulls the outer wall inward (smaller outer extent)', async () => {
    const outerX = (g) => {
      const body = g.slice(g.indexOf('; --- layer 1/'));
      let inF = false, mx = -Infinity;
      for (const ln of body.split('\n')) { if (ln.startsWith('; FEATURE:')) { inF = ln.includes('outer-wall'); continue; } if (inF) { const m = ln.match(/^G1 X([-\d.]+) Y[-\d.]+.*E/); if (m) mx = Math.max(mx, +m[1]); } }
      return mx;
    };
    const normal = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, lineWidth: 0.5, supports: false });
    const precise = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, lineWidth: 0.5, preciseWall: true, supports: false });
    assert.ok(outerX(precise.gcode) < outerX(normal.gcode), `precise wall should be inset (normal=${outerX(normal.gcode)} precise=${outerX(precise.gcode)})`);
    assert.ok(!precise.gcode.includes('NaN'));
  });
  it('precise_wall off byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, preciseWall: false, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});

describe('native-slicer: travel_speed_z + retract_restart_extra', () => {
  it('travel_speed_z sets the Z-hop feedrate', async () => {
    const r = await sliceMeshToGcode(box(20, 20, 6), { layerHeight: 0.2, zHop: 0.4, travelSpeedZ: 12, supports: false });
    assert.match(r.gcode, /G1 Z[\d.]+ F720\b/, 'z-hop at 12 mm/s = F720');
  });
  it('retract_restart_extra primes extra filament on unretract', async () => {
    const none = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.3, retraction: 1, supports: false });
    const extra = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.3, retraction: 1, retractRestartExtra: 0.1, supports: false });
    // Final E accumulates the extra primes → higher total.
    const lastE = (g) => { const m = [...g.matchAll(/E(-?\d+\.\d+)/g)]; return m.length ? +m[m.length - 1][1] : 0; };
    assert.ok(lastE(extra.gcode) > lastE(none.gcode), 'restart extra raises cumulative E');
  });
  it('both unset byte-identical', async () => {
    const a = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, zHop: 0.4, supports: false });
    const b = await sliceMeshToGcode(box(20, 20, 4), { layerHeight: 0.2, zHop: 0.4, travelSpeedZ: 0, retractRestartExtra: 0, supports: false });
    assert.equal(b.gcode, a.gcode);
  });
});
