/**
 * Native Slicer Engine — pure-JS mesh-to-G-code slicing pipeline.
 *
 * This is the project's own slicer (not a wrapper around any external
 * binary). Geometry lives in native-slicer-geo.js; this file drives the
 * pipeline and emits G-code.
 *
 * Features:
 *   - Multiple perimeters (walls), hole-aware (walls on both sides of a
 *     pocket, infill excluded from holes via even-odd scanline).
 *   - Solid top/bottom shells (configurable layer counts) with a
 *     cross-hatch grid; sparse infill (lines or grid) in between.
 *   - Skirt (adhesion priming loops) and brim (loops fused to the part).
 *   - Profile-driven start/end G-code (machine_start_gcode /
 *     machine_end_gcode) with a Marlin/Klipper-compatible default.
 *   - Trapezoidal-free but reasonable extrusion model (rectangular path
 *     cross-section) and per-feature speeds.
 *
 * It is honest about its limits: no tree/organic supports, no Arachne
 * variable-width walls, no bridging detection, no multi-material purge.
 * For those, a full desktop slicer is still king. For simple-to-medium
 * parts this produces clean, printable G-code entirely within our stack.
 */

import {
  sliceLayer, offsetPolygon, lineInfill, regionInfill, solidInfill,
  patternInfill, buildRegions, EPS, PI, _bbox, _isCCW, _signedArea, _near,
  _chainSegments, _pointInPoly,
} from './native-slicer-geo.js';
import { buildSurfaceClassifier } from './native-slicer-surfaces.js';

const FILAMENT_DIAM = 1.75;

// Re-export the geometry primitives so existing importers/tests keep working.
export { sliceLayer, offsetPolygon, lineInfill, regionInfill, solidInfill, buildRegions };

// ── G-code emission ─────────────────────────────────────────────────

function _defaultStart(s) {
  return [
    `M140 S${s.bedTemp}`,
    `M104 S${s.nozzleTemp}`,
    `G28 ; home`,
    `M190 S${s.bedTemp}`,
    `M109 S${s.nozzleTemp}`,
    `G92 E0`,
    `G90`,
    `M82`,
    `M106 S${Math.round(s.fanSpeed * 2.55)}`,
  ].join('\n') + '\n';
}

function _defaultEnd() {
  return [
    `M104 S0`,
    `M140 S0`,
    `M107`,
    `G28 X Y`,
    `M84`,
  ].join('\n') + '\n';
}

/**
 * Convert a stack of layers (each = { perimeters: [[poly]], infill:
 * [[seg]] }) into a G-code string.
 *
 * @param {Array<{perimeters:number[][][], infill:number[][][]}>} layers
 * @param {object} settings — layerHeight, lineWidth, printSpeed,
 *   travelSpeed, retraction, bedTemp, nozzleTemp, filamentDiam,
 *   fanSpeed, firstLayerSpeed, material, startGcode, endGcode.
 */
export function layersToGcode(layers, settings) {
  const s = {
    layerHeight: 0.2, lineWidth: 0.4, printSpeed: 60, travelSpeed: 120,
    retraction: 1.5, bedTemp: 60, nozzleTemp: 215, filamentDiam: FILAMENT_DIAM,
    fanSpeed: 100, firstLayerSpeed: 20, bedSize: [256, 256], material: 'PLA',
    startGcode: null, endGcode: null,
    ...settings,
  };
  // Extrusion factor: volume of a 1 mm path = lineWidth * layerHeight,
  // E (mm filament) = volume / (π · (filamentDiam/2)²).
  const efactor = (s.lineWidth * s.layerHeight) / (PI * (s.filamentDiam / 2) ** 2);

  let g = '';
  g += `; Generated by 3DPrintForge native slicer\n`;
  g += `; Layers: ${layers.length}, layer height: ${s.layerHeight} mm\n`;
  g += `; Material: ${s.material}, nozzle ${s.nozzleTemp}C, bed ${s.bedTemp}C\n`;
  g += `; estimated_time: 0\n`;
  g += (s.startGcode ? _interp(s.startGcode, s) + '\n' : _defaultStart(s));

  let e = 0;
  let curX = 0, curY = 0, curZ = 0;

  // Prime line (skip when a custom start gcode already primes).
  if (!s.startGcode) {
    g += `; --- prime line ---\n`;
    g += `G1 Z0.3 F${s.travelSpeed * 60}\n`;
    g += `G1 X20 Y20 F${s.travelSpeed * 60}\n`;
    g += `G1 X80 Y20 E${(60 * efactor).toFixed(4)} F${s.firstLayerSpeed * 60}\n`;
    g += `G92 E0\n`;
    curX = 80; curY = 20; curZ = 0.3;
  }

  const emitPath = (pts, speed, closed, flow = 1) => {
    if (pts.length < 2) return;
    const ef = efactor * flow;
    const first = pts[0];
    // Retract, travel, unretract.
    e -= s.retraction; g += `G1 E${e.toFixed(4)} F${(s.travelSpeed * 60).toFixed(0)}\n`;
    g += `G0 X${first[0].toFixed(3)} Y${first[1].toFixed(3)} F${s.travelSpeed * 60}\n`;
    e += s.retraction; g += `G1 E${e.toFixed(4)} F${(s.travelSpeed * 60).toFixed(0)}\n`;
    curX = first[0]; curY = first[1];
    for (let i = 1; i < pts.length; i++) {
      const p = pts[i];
      const d = Math.hypot(p[0] - curX, p[1] - curY);
      e += d * ef;
      g += `G1 X${p[0].toFixed(3)} Y${p[1].toFixed(3)} E${e.toFixed(4)} F${speed * 60}\n`;
      curX = p[0]; curY = p[1];
    }
    if (closed) {
      const d = Math.hypot(first[0] - curX, first[1] - curY);
      if (d > EPS) {
        e += d * ef;
        g += `G1 X${first[0].toFixed(3)} Y${first[1].toFixed(3)} E${e.toFixed(4)} F${speed * 60}\n`;
        curX = first[0]; curY = first[1];
      }
    }
  };

  layers.forEach((layer, layerIdx) => {
    const z = (layerIdx + 1) * s.layerHeight;
    const speed = layerIdx === 0 ? s.firstLayerSpeed : s.printSpeed;
    g += `; --- layer ${layerIdx + 1}/${layers.length} z=${z.toFixed(3)} ---\n`;
    g += `G1 Z${z.toFixed(3)} F${s.travelSpeed * 60}\n`;
    curZ = z;
    if (layerIdx === 1) g += `M106 S${Math.round(s.fanSpeed * 2.55)}\n`;

    // Typed paths (new) carry a per-feature tag so the preview can colour
    // walls / infill / support / skirt distinctly, like a desktop slicer.
    // Legacy {perimeters, infill} layers still work.
    const paths = layer.paths || [
      ...(layer.perimeters || []).map((p) => ({ feature: 'wall', closed: true, pts: p })),
      ...(layer.infill || []).map((sgm) => ({ feature: 'sparse', closed: false, pts: sgm })),
    ];
    let curFeature = null;
    for (const path of paths) {
      if (!path.pts || path.pts.length < 2) continue;
      if (path.feature !== curFeature) { g += `; FEATURE:${path.feature}\n`; curFeature = path.feature; }
      // Ironing runs at the print speed but scaled down for a fine finish.
      const pspeed = path.feature === 'ironing' ? Math.max(20, speed * 0.4) : speed;
      emitPath(path.pts, pspeed, !!path.closed, path.flow ?? 1);
    }
  });

  g += `; --- finished ---\n`;
  e -= s.retraction; g += `G1 E${e.toFixed(4)} F${s.travelSpeed * 60}\n`;
  g += `G1 Z${(curZ + 5).toFixed(3)} F${s.travelSpeed * 60}\n`;
  g += (s.endGcode ? _interp(s.endGcode, s) + '\n' : _defaultEnd());
  return g;
}

/** Substitute common profile placeholders in start/end G-code. Tokens
 *  must be bracketed ([name] or {name}) so we consume them whole. */
function _interp(tpl, s) {
  const nozzle = /[\[{]\s*(nozzle_temperature_initial_layer|nozzle_temperature|first_layer_temperature|temperature)\s*[\]}]/gi;
  const bed = /[\[{]\s*(bed_temperature_initial_layer|bed_temperature|first_layer_bed_temperature)\s*[\]}]/gi;
  return String(tpl).replace(nozzle, s.nozzleTemp).replace(bed, s.bedTemp);
}

// ── Pipeline orchestrator ───────────────────────────────────────────

/**
 * End-to-end slicing: mesh → G-code. Repairs + recenters the mesh, then
 * slices into walls / shells / infill / skirt.
 */
export async function sliceMeshToGcode(mesh, settings = {}) {
  const s = {
    layerHeight: 0.2, lineWidth: 0.4, perimeters: 2, infillDensity: 0.2,
    infillAngle: 45, infillPattern: 'grid', topLayers: 4, bottomLayers: 4,
    skirtLoops: 1, skirtGap: 3, brimWidth: 0,
    supports: false, supportDensity: 0.2, supportGridRes: 2, supportXYGap: 0.8, supportZGap: 1, supportInterface: 2,
    ironing: false, ironingFlow: 0.15, ironingSpacingFactor: 0.5,
    ...settings,
  };
  const wallLoops = Math.max(1, s.perimeters | 0);
  const lw = s.lineWidth;

  const { autoRepair } = await import('./mesh-repair.js');
  const { recenterToOrigin, meshStats } = await import('./mesh-transforms.js');
  const repaired = autoRepair(mesh).mesh;
  const recentered = recenterToOrigin(repaired).mesh;
  const stats = meshStats(recentered);
  const layerHeight = s.layerHeight;
  const numLayers = Math.max(1, Math.floor(stats.bbox.size[2] / layerHeight));

  // Pass 1 — slice every layer into regions (needed up-front for supports).
  const layerRegions = [];
  for (let i = 0; i < numLayers; i++) {
    const z = (i + 0.5) * layerHeight;
    layerRegions.push(buildRegions(sliceLayer(recentered, z)));
  }

  // Supports (optional) — overhang columns down to the bed.
  let supportSegs = null;
  if (s.supports) {
    const { generateSupports } = await import('./native-slicer-support.js');
    supportSegs = generateSupports(layerRegions, {
      lineWidth: lw, gridRes: s.supportGridRes, density: s.supportDensity, xyGap: s.supportXYGap, zGapLayers: s.supportZGap, interfaceLayers: s.supportInterface,
    });
  }

  // Surface classifier — marks infill solid on real top/bottom faces
  // (including over holes/steps), not just the global first/last N layers.
  const surfaces = s.solidSurfaces === false ? null : buildSurfaceClassifier(layerRegions, {
    gridRes: s.surfaceGridRes ?? 2, topLayers: s.topLayers, bottomLayers: s.bottomLayers,
  });
  const midSolid = (surfaces, i, sg) => surfaces.isSolidPoint(i, (sg[0][0] + sg[1][0]) / 2, (sg[0][1] + sg[1][1]) / 2);

  // Pass 2 — walls + shells + infill (+ supports) per layer, as typed
  // paths so the preview can colour each feature like a desktop slicer.
  const layers = [];
  for (let i = 0; i < numLayers; i++) {
    const regions = layerRegions[i];
    const adhesion = [];   // skirt/brim (layer 0)
    const walls = [];      // outer/inner/hole walls
    const fills = [];      // solid/sparse infill
    const globalSolid = i < s.bottomLayers || i >= numLayers - s.topLayers;

    for (const region of regions) {
      // Outer walls: shrink inward wall-by-wall (negative = inward).
      let inner = region.outer;
      walls.push({ feature: 'outer-wall', closed: true, pts: inner });
      for (let p = 1; p < wallLoops; p++) {
        inner = offsetPolygon(inner, -lw);
        if (!inner || inner.length < 3) break;
        walls.push({ feature: 'inner-wall', closed: true, pts: inner });
      }
      // Hole walls: grow each hole outward into the solid.
      const grownHoles = [];
      for (const hole of region.holes) {
        let hw = hole;
        walls.push({ feature: 'inner-wall', closed: true, pts: hw });
        for (let p = 1; p < wallLoops; p++) {
          hw = offsetPolygon(hw, lw);
          if (!hw || hw.length < 3) break;
          walls.push({ feature: 'inner-wall', closed: true, pts: hw });
        }
        grownHoles.push(hw);
      }
      // Infill region = innermost outer wall shrunk half a line, holes grown half a line.
      const infOuter = offsetPolygon(inner, -lw * 0.5);
      const infHoles = grownHoles.map(h => offsetPolygon(h, lw * 0.5)).filter(h => h && h.length >= 3);
      if (infOuter && infOuter.length >= 3) {
        const infRegion = { outer: infOuter, holes: infHoles };
        const baseAngle = s.infillAngle + (i % 2) * 90;
        if (!surfaces || globalSolid) {
          // No surface detection (or a global shell layer): fill uniformly.
          const segs = globalSolid
            ? solidInfill(infRegion, baseAngle, lw)
            : patternInfill(infRegion, s.infillDensity, baseAngle, lw, s.infillPattern);
          const feat = globalSolid ? 'solid' : 'sparse';
          for (const sg of segs) fills.push({ feature: feat, closed: false, pts: sg });
        } else {
          // Per-surface: solid where this is a top/bottom face, sparse elsewhere.
          const solidSegs = solidInfill(infRegion, baseAngle, lw).filter((sg) => midSolid(surfaces, i, sg));
          const sparseSegs = patternInfill(infRegion, s.infillDensity, baseAngle, lw, s.infillPattern).filter((sg) => !midSolid(surfaces, i, sg));
          for (const sg of solidSegs) fills.push({ feature: 'solid', closed: false, pts: sg });
          for (const sg of sparseSegs) fills.push({ feature: 'sparse', closed: false, pts: sg });
        }
        // Ironing: a fine, low-flow pass over the true top skin to smooth it.
        if (s.ironing && surfaces) {
          const ironAngle = s.infillAngle + 45 + (i % 2) * 90;
          const ironSegs = regionInfill(infRegion, 1.0, ironAngle, lw * (s.ironingSpacingFactor ?? 0.5))
            .filter((sg) => surfaces.isTopPoint(i, (sg[0][0] + sg[1][0]) / 2, (sg[0][1] + sg[1][1]) / 2));
          for (const sg of ironSegs) fills.push({ feature: 'ironing', closed: false, pts: sg, flow: s.ironingFlow ?? 0.15 });
        }
      }
    }

    // Skirt + brim on the first layer only.
    if (i === 0) {
      for (const region of regions) {
        const brimLoops = Math.max(0, Math.round((s.brimWidth || 0) / lw));
        let ring = region.outer;
        for (let b = 0; b < brimLoops; b++) {
          ring = offsetPolygon(ring, lw);
          if (!ring || ring.length < 3) break;
          adhesion.push({ feature: 'brim', closed: true, pts: ring });
        }
        let sk = offsetPolygon(region.outer, s.skirtGap + (brimLoops * lw));
        for (let k = 0; k < s.skirtLoops; k++) {
          if (!sk || sk.length < 3) break;
          adhesion.push({ feature: 'skirt', closed: true, pts: sk });
          sk = offsetPolygon(sk, lw);
        }
      }
    }

    // Support hatch.
    const support = [];
    if (supportSegs && supportSegs[i]) for (const sg of supportSegs[i]) support.push({ feature: 'support', closed: false, pts: sg });

    // Print order: adhesion → walls → infill → support.
    layers.push({ paths: [...adhesion, ...walls, ...fills, ...support] });
  }

  const gcode = layersToGcode(layers, s);
  return {
    gcode,
    layers: layers.length,
    bbox: stats.bbox,
    triangles: recentered.indices.length / 3,
    supported: !!s.supports,
  };
}

export const _internals = { _chainSegments, _signedArea, _isCCW, _near, _bbox, _pointInPoly, EPS };
